### ISSUE TITLE
With the latest Github build Yatabar is completely gone

### ISSUE THREAD

**Issue by keolwyn** [KaybeHud/Yatabar#2]
With the last Github build Yatabar is completely gone from the screen on my level 27 shaman. 

(bar should be inside the red square)
![Screenshot_11](https://user-images.githubusercontent.com/5385483/120003638-9c3fbd80-bfde-11eb-8105-0b1d609d94ef.png)

I believe that reason for this is the following:

in `GetTotemSpellsByElement()` (line 621) function you are checking if there are any totems for the certain element

```lua
if Yatabar.totemsFound[element] == false then
    if Yatabar.config.debugOn then
        Yatabar:AddDebugText("GetTotemSpellsByElement: skip element:"..element)
    end
    print("GetTotemSpellsByElement: skip element:"..element)
    break
end
```

But, if you check `totemsFound` table through the stack output, you could see that the first element is actually an `AIR`

![Screenshot_12](https://user-images.githubusercontent.com/5385483/120004892-f7be7b00-bfdf-11eb-93af-f92832e79282.png)

and there are no air totems on level 27, so the function will `break`, skip the rest of the code, and don't get any info about the rest totems. The simple fix is to remove the `break` statement and the bar is back.

![Screenshot_4](https://user-images.githubusercontent.com/5385483/120005473-88955680-bfe0-11eb-9af5-df0768e9f6fc.png)

**Comment by KaybeHud** [comment]
Hey, yes, you are right, the break is wrong there, it had written this quickly

**Comment by keolwyn** [comment]
No worries, great addon, thanks for your work :)
