### ISSUE TITLE
Impossible to change set in combat

### ISSUE THREAD

**Issue by aldur91** [KaybeHud/Yatabar#8]
Hi, I have problems with totem switch while in combat.

pop up key = no key -> I can't modify my set while in combat (pop up, select with right click). I can still summon other totems in combat (pop up left click).

pop up key = CTRL   ->   I can't modify my set while in combat (pop up, select with right click). I can't summon other totems in combat (pop up left click).

**Comment by KaybeHud** [comment]
This is intended. You can not change them during the fight. 
If you do this in options menu, you will get a message in the chat window. I will add this message for right click in the next version.
